name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to download
        required: false
        type: string
        default: dist
    outputs:
      result:
        description: Result of the reusable workflow
        value: ${{ jobs.deploy.outputs.outcome }}
      
jobs: 
  deploy:
    outputs:
      outcome: ${{ steps.outcomeset.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
        with: 
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Print Random
        run: echo 'This is from reusable workflow'
      - name: Set result output
        id: outcomeset
        run: echo step-result=success >> $GITHUB_OUTPUT